---
title: Mandala
hero_image: images/banner.png
description: Maak door de computer gegenereerde mandala's in Scratch
meta_title: Scratch-programmeerprojecten voor kinderen en tieners | Mandala
meta_description: Leer coderen in Scratch met de programmeerprojecten voor kinderen en tieners van de Raspberry Pi Foundation. Maak een Scratch-programma dat mandala's genereert.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - title: Je gaat maken
  - title: Maak een patroon door vormen te klonen
  - title: Maak een mandala
    completion:
      - engaged
  - title: Stel je sprite in
  - title: Mandala inkleuren
  - title: Maak nog een mandala
  - title: Kies je mandala
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 2
      passing_score: 2
    completion:
      - external
  - title: Verbeter je project
  - title: Wat kun je verder nog doen?
