title: mandala
hero_image: images/banner.png
description: mandala description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-17"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
