---
title: मंडला
hero_image: images/banner.png
description: Scratch में कंप्यूटर जनित मंडला बनाएं
meta_title: Scratch coding projects for kids and teens | Mandala
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Create a Scratch program that generates mandalas.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: परिचय
  - 
    title: आकृतियों को एक पैटर्न बनाने के लिए क्लोन करें
  - 
    title: एक मंडला बनाओ
    completion:
      - engaged
  - 
    title: अपना स्प्राइट सेट करें
  - 
    title: एक और मंडला बनाएं
  - 
    title: अपना मंडला चुनें
  - 
    title: मंडला में रंग भरना
    completion:
      - internal
  - 
    title: सोचिए
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 2
      passing_score: 2
    completion:
      - external
  - 
    title: अपना प्रोजेक्ट अपग्रेड करें
  - 
    title: आगे क्या?
