---
title: मंडला
hero_image: images/banner.png
description: Scratch में कंप्यूटर जनित मंडला बनाएं
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: परिचय
  - 
    title: आकृतियों को एक पैटर्न बनाने के लिए क्लोन करें
  - 
    title: एक मंडला बनाओ
    completion:
      - engaged
  - 
    title: अपना स्प्राइट सेट करें
  - 
    title: Mandala colouring
  - 
    title: Create another mandala
  - 
    title: Choose your mandala
    completion:
      - internal
  - 
    title: सोचिए
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 2
      passing_score: 2
    completion:
      - external
  - 
    title: अपना प्रोजेक्ट अपग्रेड करें
  - 
    title: आगे क्या?
