---
title: Mandala
hero_image: images/banner.png
description: Make computer generated mandalas in Scratch
meta_title: Scratch coding projects for kids and teens | Mandala
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Create a Scratch program that generates mandalas.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: Clone shapes to make a pattern
  - 
    title: Make a mandala
    completion:
      - engaged
  - 
    title: Setup your sprite
  - 
    title: Mandala colouring
  - 
    title: Create another mandala
  - 
    title: Choose your mandala
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 2
      passing_score: 2
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: What next?
