---
title: Mandala
hero_image: images/banner.png
description: Gwneud mandalas a gynhyrchir gan gyfrifiadur yn Scratch
meta_title: Scratch coding projects for kids and teens | Mandala
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Create a Scratch program that generates mandalas.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Byddi di'n creu
  - 
    title: Clonio siapiau i wneud patrwm
  - 
    title: Gwna mandala
    completion:
      - engaged
  - 
    title: Sefydla dy gorlun
  - 
    title: Lliwio mandala
  - 
    title: Creu mandala arall
  - 
    title: Dewisa dy fandala
    completion:
      - internal
  - 
    title: Cwis cyflym
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 2
      passing_score: 2
    completion:
      - external
  - 
    title: Uwchraddio dy brosiect
  - 
    title: Beth nesaf?
