---
title: ماندالة
hero_image: images/banner.png
description: جعل الحاسوب يولد ماندالات في سكراتش
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: استنساخ الأشكال لعمل نمط
  - 
    title: اصنع ماندالة
    completion:
      - engaged
  - 
    title: تجهيز كائنك
  - 
    title: اخلق ماندالة أخرى
  - 
    title: اختر ماندالتك
  - 
    title: تلوين ماندالة
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 2
      passing_score: 2
    completion:
      - external
  - 
    title: رق مشروعك
  - 
    title: ما التالي؟
