---
title: Mandala
hero_image: images/banner.png
description: Créer des mandalas générés par ordinateur dans Scratch
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Tu feras
  - 
    title: Cloner des formes pour créer un motif
  - 
    title: Créer un mandala
    completion:
      - engaged
  - 
    title: Configurer ton sprite
  - 
    title: Colorisation du mandala
  - 
    title: Créer un autre mandala
  - 
    title: Choisir ton mandala
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 2
      passing_score: 2
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
